type Conversation {
  from: Party!
  offer: Offer!
  isActive: Boolean!
}

type Offer {
  airtableRecordId: ID! @unique
  owner: Party!
  conversations: [Conversation!]! @relation
}

type Party {
  phone: String!
  offers: [Offer!]! @relation
  conversations: [Conversation!]! @relation
}
